pattern_cols: 10
pattern_rows: 7
center_distance_mm: 40

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

camera_name: "hikrobot"
exposure_ms: 3
gain: 10.0
vid_pid: "2bdf:0001"

#####-----cboard参数-----#####
serial_device: "/dev/ttyACM0"  # 虚拟串口设备路径
serial_baudrate: 115200         # 波特率